export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const WORKSPACE_MEMBERS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_WORKSPACE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const PROJECT_MEMBERS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PROJECT_MEMBERS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const HISTORIES_ID = process.env.NEXT_PUBLIC_APPWRITE_HISTORIES_ID!;
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
